- name: Configuration | Disable C-state
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash intel_idle.max_cstate=0 processor.max_cstate=1"'
    state: present
  notify: update grub

- name: Configuration | Set CPU governor to performance
  command: cpufreq-set -r -g performance
  ignore_errors: true  # For VM systems

- name: Configuration | Set CPU governor to performance using sysfs
  shell: echo performance | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
  args:
    executable: /bin/bash
  ignore_errors: true # For VM systems

- name: Configuration | Get list of CPUs
  shell: lscpu | grep -E 'CPU|Thread'
  register: cpu_info
  notify: show cpu